# Generated by Django 4.2.11 on 2024-04-19 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postlikeusers',
            old_name='article',
            new_name='post',
        ),
    ]
