# Generated by Django 4.2.11 on 2024-04-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_article_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='images/'),
        ),
    ]
