# Generated by Django 4.2.11 on 2024-04-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=1, max_length=1000, upload_to='images/'),
            preserve_default=False,
        ),
    ]
