# Generated by Django 4.2.11 on 2024-04-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_article_comment_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='feed_images/')),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('user_id', models.TextField()),
                ('like_count', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='images/'),
        ),
    ]
