# Generated by Django 4.2.11 on 2024-04-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
