# Generated by Django 4.2.11 on 2024-04-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
