# Generated by Django 4.2.11 on 2024-04-22 09:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_followings"),
        ("accounts", "0004_user_profile_img_name"),
    ]

    operations = []
